
name: Tests and build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: nologin

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: 'npm'

      - name: install npm packages
        run: npm ci
      
      - name: build npm project
        run: npm run build

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/polytech-exam-2024/bintz-fabien/angular:fabien-bintz
