
name: Tests and build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: nologin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
  
    - name: Tests maven
      run: mvn -B clean test --file pom.xml
      
    - name: Build maven
      run: mvn -B package --file pom.xml

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/polytech2024
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_API_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: rg.fr-par.scw.cloud/polytech-exam-2024/bintz-fabien/java:fabien-bintz

